# Split anndata object by ancestry - AFR (102), EUR (81), EAS (22), SAS (62)

In [1]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import scipy as sci
import scanpy as sc
import copy
import scvi
import re
#import plotnine as p9

%config InlineBackend.print_figure_kwargs={'facecolor' : "w"}
%config InlineBackend.figure_format='retina'
%matplotlib inline  

pd.set_option('display.max_columns', None)
sc.set_figure_params(figsize=(5, 5),dpi=200)

/opt/view/lib/python3.11/site-packages/anndata/utils.py:429: FutureWarning: Importing read_csv from `anndata` is deprecated. Import anndata.io.read_csv instead.
  warnings.warn(msg, FutureWarning)
/opt/view/lib/python3.11/site-packages/anndata/utils.py:429: FutureWarning: Importing read_excel from `anndata` is deprecated. Import anndata.io.read_excel instead.
  warnings.warn(msg, FutureWarning)
/opt/view/lib/python3.11/site-packages/anndata/utils.py:429: FutureWarning: Importing read_hdf from `anndata` is deprecated. Import anndata.io.read_hdf instead.
  warnings.warn(msg, FutureWarning)
/opt/view/lib/python3.11/site-packages/anndata/utils.py:429: FutureWarning: Importing read_loom from `anndata` is deprecated. Import anndata.io.read_loom instead.
  warnings.warn(msg, FutureWarning)
/opt/view/lib/python3.11/site-packages/anndata/utils.py:429: FutureWarning: Importing read_mtx from `anndata` is deprecated. Import anndata.io.read_mtx instead.
  warnings.warn(msg, FutureWarning)
/opt/view/lib/python3.11/site-packages/anndata/utils.py:429: FutureWarning: Importing read_text from `anndata` is deprecated. Import anndata.io.read_text instead.
  warnings.warn(msg, FutureWarning)
/opt/view/lib/python3.11/site-packages/anndata/utils.py:429: FutureWarning: Importing read_umi_tools from `anndata` is deprecated. Import anndata.io.read_umi_tools instead.
  warnings.warn(msg, FutureWarning)
/opt/view/lib/python3.11/site-packages/anndata/utils.py:429: FutureWarning: Importing read_csv from `anndata` is deprecated. Import anndata.io.read_csv instead.
  warnings.warn(msg, FutureWarning)
/opt/view/lib/python3.11/site-packages/anndata/utils.py:429: FutureWarning: Importing read_loom from `anndata` is deprecated. Import anndata.io.read_loom instead.
  warnings.warn(msg, FutureWarning)
/opt/view/lib/python3.11/site-packages/anndata/utils.py:429: FutureWarning: Importing read_text from `anndata` is deprecated. Import anndata.io.read_text instead.
  warnings.warn(msg, FutureWarning)
/opt/view/lib/python3.11/site-packages/anndata/utils.py:429: FutureWarning: Importing CSCDataset from `anndata.experimental` is deprecated. Import anndata.abc.CSCDataset instead.
  warnings.warn(msg, FutureWarning)
/opt/view/lib/python3.11/site-packages/anndata/utils.py:429: FutureWarning: Importing CSRDataset from `anndata.experimental` is deprecated. Import anndata.abc.CSRDataset instead.
  warnings.warn(msg, FutureWarning)
/opt/view/lib/python3.11/site-packages/anndata/utils.py:429: FutureWarning: Importing read_elem from `anndata.experimental` is deprecated. Import anndata.io.read_elem instead.
  warnings.warn(msg, FutureWarning)
/opt/view/lib/python3.11/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [8]:
SLEmap=sc.read("/lustre/scratch127/open-targets/Projects/OTAR2064/working/users/hj10/Results/2_YASCP_final/5_QC_afterHLA_afterClusterremoval/QTLite/testrun_input_n281_noOBSM.h5ad")
SLEmap.obs

,experiment_id,condition,recruitment_centre,sex,externalID,WGS_ID,poolID,n_genes_by_counts,log1p_n_genes_by_counts,total_counts,log1p_total_counts,pct_counts_gene_group__mito_transcript,log1p_total_counts_gene_group__ribo_protein,log10_ngenes_by_count,normalization_factor,Azimuth:predicted.celltype.l1,Azimuth:predicted.celltype.l1.score,Azimuth:mapping.score.celltype.l1,Azimuth:predicted.celltype.l2,Azimuth:predicted.celltype.l2.score,Azimuth:mapping.score.celltype.l2,Celltypist:Immune_All_Low:n_counts,Celltypist:Immune_All_Low:predicted_labels,Celltypist:Immune_All_Low:over_clustering,Celltypist:Immune_All_Low:majority_voting,Celltypist:Immune_All_Low:conf_score,Celltypist:Immune_All_High:n_counts,Celltypist:Immune_All_High:predicted_labels,Celltypist:Immune_All_High:over_clustering,Celltypist:Immune_All_High:majority_voting,Celltypist:Immune_All_High:conf_score,VDJ,_scvi_labels,_scvi_batch,leiden_totalVI,annotation_BTother,Celltype_level1,Celltype_level2,T_cluster,donor_id,Celltype_level0
index,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
AAACCTGTCCTATTCA-1-SLE_WGS13446475_LDP01__donor,SLE_WGS13446475_LDP01,SLE,Kings,F,EQTL083P,SLE_WGS13446475,LDP01,2748,7.918992,9784.0,9.188606,0.511038,7.884200,0.861797,9784.0,B,0.972145262054306,0.988524387890834,B memory,0.454549172518525,0.988524387890834,9784.0,Age-associated B cells,2,Age-associated B cells,0.999181776250646,9784.0,B cells,2,B cells,0.998594147977526,NaN,0,0,21,B,Naive_B_cells,Naive_B_cells,NA,SLE_WGS13446475,All
AAACGGGGTTGCGTTA-1-SLE_WGS13446475_LDP01__donor,SLE_WGS13446475_LDP01,SLE,Kings,F,EQTL083P,SLE_WGS13446475,LDP01,1779,7.484369,4606.0,8.435332,1.020408,6.966967,0.887220,4606.0,NK,0.901415102308412,0.977126889715796,NK_CD56bright,0.52491221770141,0.977126889715796,4606.0,NK cells,0,CD16+ NK cells,0.0708510702346563,4606.0,ILC,0,ILC,0.99989144988027,NaN,0,0,24,Other,CD56Bright_NK_cells,CD56Bright_NK_cells,NA,SLE_WGS13446475,All
AAAGATGCACGCTTTC-1-SLE_WGS13446475_LDP01__donor,SLE_WGS13446475_LDP01,SLE,Kings,F,EQTL083P,SLE_WGS13446475,LDP01,1242,7.125283,3298.0,8.101375,0.758035,7.049255,0.879449,3298.0,NK,0.98407663926649,0.999135264387835,NK,0.562969443244527,0.999135264387835,3298.0,NK cells,0,CD16+ NK cells,0.045185300626458,3298.0,ILC,0,ILC,0.993330058443046,NaN,0,0,24,Other,CD56Dim_NK_cells,CD56Dim_NK_cells,NA,SLE_WGS13446475,All
AAAGATGCACTTAAGC-1-SLE_WGS13446475_LDP01__donor,SLE_WGS13446475_LDP01,SLE,Kings,F,EQTL083P,SLE_WGS13446475,LDP01,1247,7.129298,3434.0,8.141772,0.728014,7.066467,0.875577,3434.0,CD4 T,1.0,0.99147377595226,CD4 TCM,0.81208480584909,0.99147377595226,3434.0,Tcm/Naive helper T cells,4,Tcm/Naive helper T cells,0.8427473161879951,3434.0,T cells,4,T cells,0.9997996498249444,TCR,0,0,27,T,Naive_CD4_T_cells,Naive_CD4_T_cells,21,SLE_WGS13446475,All
AAAGCAAAGATCTGAA-1-SLE_WGS13446475_LDP01__donor,SLE_WGS13446475_LDP01,SLE,Kings,F,EQTL083P,SLE_WGS13446475,LDP01,942,6.849066,3417.0,8.136811,1.082821,7.419980,0.841638,3417.0,CD4 T,0.97604889871704,0.981848325930261,CD4 Naive,0.879846881137276,0.981848325930261,3417.0,Tcm/Naive helper T cells,8,Tcm/Naive helper T cells,0.9993313697095632,3417.0,T cells,8,T cells,0.9999992926505225,TCR,0,0,27,T,Naive_CD4_T_cells,Naive_CD4_T_cells,21,SLE_WGS13446475,All
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
TTTGGTTCAGGGTACA-1-SLE_map14783141_LDP37__donor,SLE_map14783141_LDP37,SLE,Imperial,F,S104,SLE_map14783141,LDP37,2048,7.625107,5177.0,8.552175,1.062391,7.368340,0.891562,5177.0,B,1.0,0.933196017236146,B naive,0.943943398330885,0.933196017236146,5177.0,Naive B cells,8,Naive B cells,0.9990347591818896,5177.0,B cells,8,B cells,0.9999962181013616,BCR,0,36,1,B,Naive_B_cells,Naive_B_cells,NA,SLE_map14783141,All
TTTGGTTTCAGTCCCT-1-SLE_map14783141_LDP37__donor,SLE_map14783141_LDP37,SLE,Imperial,F,S104,SLE_map14783141,LDP37,1706,7.442493,3695.0,8.215007,3.761840,6.773080,0.905922,3695.0,B,1.0,0.831490592526736,B naive,0.976474963344939,0.831490592526736,3695.0,Naive B cells,20,Naive B cells,0.987242509123214,3695.0,B cells,20,B cells,0.9999999928278952,BCR,0,36,1,B,Naive_B_cells,Naive_B_cells,NA,SLE_map14783141,All
TTTGGTTTCGGTTAAC-1-SLE_map14783141_LDP37__donor,SLE_map14783141_LDP37,SLE,Imperial,F,S104,SLE_map14783141,LDP37,2185,7.689829,5282.0,8.572249,2.442257,7.202661,0.897027,5282.0,CD8 T,0.936699234768641,0.945268704577058,CD8 TEM,0.936699234768641,0.945268704577058,5282.0,Tem/Trm cytotoxic T cells,19,Tem/Temra cytotoxic T cells,0.9960462654735444,5282.0,T cells,19,T cells,0.999989386080858,TCR,0,36,3,T,TEMRA,TEMRA,6,SLE_map14783141,All
TTTGTCAAGATCTGCT-1-SLE_map14783141_LDP37__donor,SLE_map14783141_LDP37,SLE,Imperial,F,S104,SLE_map14783141,LDP37,1668,7.419980,3882.0,8.264363,2.988151,7.038784,0.897784,3882.0,CD8 T,0.935073171531549,0.953343230333327,CD8 TEM,0.730176942847057,0.953343230333327,3882.0,Tem/Trm cytotoxic T cells,6,Tem/Trm cytotoxic T cells,0.9967595521393606,3882.0,T cells,6,T cells,0.9999999228892832,TCR,0,36,9,T,EM_CD8_T_cells,EM_CD8_T_cells,2,SLE_map14783141,All
TTTGTCATCATGTCTT-1-SLE_map14783141_LDP37__donor,SLE_map14783141_LDP37,SLE,Imperial,F,S104,SLE_map14783141,LDP37,1747,7.466228,4039.0,8.304000,2.376826,7.031741,0.899070,4039.0,CD8 T,0.9809182216931,0.961255972772291,CD8 TEM,0.902039217937397,0.961255972772291,4039.0,Tem/Trm cytotoxic T cells,22,Tem/Trm cytotoxic T cells,0.9684964443656396,4039.0,T cells,22,T cells,0.9999999245397488,TCR,0,36,9,T,EM_CD8_T_cells,EM_CD8_T_cells,2,SLE_map14783141,All

In [4]:
ancestry = pd.read_csv("/lustre/scratch127/open-targets/Projects/OTAR2064/working/slemap/phenotype/combined_data_tidied_sc_used_w_KING_06_11_25.csv")
ancestry

,Patient_ID,externalID,Sample_ID,Site,Recruit_centre,Date_of_consent,Sample_date,Sample_year,Year_of_Birth,Age_at_sampling,Age_decade,Ethnicity_cerner,Diagnosis_date,Diagnosis_year,Years_from_diagnosis,Age_at_diagnosis,Sex,Lupus_status,IFN_score,IFN_status,IFN_status_binary,SLEDAI_2K,SLEDAI_2K_Comments,SLEDAI_2KG,SLEDAI_2K_Clinical,cSLEDAI_2K,SLEDAI_activity,cSLEDAI_activity,Remission,LN,LN_date,LN_Class,LN_Class_tidy,Kidney_biopsies,Organ_CVS,Organ_Arterial,Organ_Venous,Organ_Lung_Fibrosis,Multiple_Sclerosis,Thyroid_Disease_Hashimotos,Graves_Disease,Type_I_Diabetes,Rheumatoid_Arthritis,Any_other_comorbidities,MMF,MMF_dose,Pred,Pred_dose,HCQ,HCQ_dose,AZA,AZA_dose,MTX,MTX_dose,TAC,TAC_dose,ASP,ASP_dose,CYC_ever,CYC_dose,CYC_date,CYC_cycles,BEL_ever,BEL_dose,BEL_date,RTX_ever,RTX_dose,RTX_date,RTX_cycles,OFA_ever,OFA_dose,OFA_date,OFA_cycles,dsDNA,dsDNA_titre,dsDNA_units,dsDNA_Ab_ever,dsDNA_date,ANA,ANA_ever,Ribosomal_P,Ro_52,Ro_60,La,Centromere,Sm,Sm_RNP,RNP_68,RNP_A,Scl70,Jo_1,MPO,PR3,LAC_status,ACA_status,ACA_IgG,ACA_IgM,B2G_status,B2G_IgG,B2G_IgM,Vitamin_D,Vitamin_D_date,TSH,TSH_date,C3_level,C4_level,Comp_date,uPCR,uPCR_units,uPCR_date,Albumin,Creatinine,eGFR,eGFR_adjust,Haemoglobin,Lymphopenia_now,Lymphopenia_ever,Lymphocyte_count,Neutrophil_count,Monocyte_count,FBC_Biochem_date,B_cell_n,B_cell_%,CD4_n,CD4_%,CD8_n,CD8_%,Lymph_subsets_date,IgA,IgG,IgM,Ig_date,C3_status,C4_status,dsDNA_SLEDAI_status,ACR_Malar,ACR_Discoid,ACR_Photosensitivity,ACR_oral_ulcers,ACR_Arthritis,ACR_serositis,ACR_seizures/psychosis,ACR_Haem,ACR_Immunologic,KBX_2,KBX_2_LN_Class,KBX_3,KBX_3_LN_Class,KBX_4,KBX_4_LN_Class,KBX_5,KBX_5_LN_Class,KBX_6,KBX_6_LN_Class,KBX_7,KBX_7_LN_Class,WGS_ID,IID,Ancestry
0,EQTL009P,EQTL009P,NaN,Guys,Kings,27/10/2020,27/10/2020,2020,1978,42,40,African,2003,2003.0,17.0,25.0,NaN,NaN,NaN,NaN,NaN,4.0,Arthritis,NaN,NaN,4.0,INACTIVE,INACTIVE,No,Yes,2007,Class III,III,1.0,No,No,No,No,No,No,No,No,No,No,Yes,1 g daily,Yes,7.5mg OD,Yes,200mg daily,No,NaN,No,NaN,No,NaN,No,NaN,Yes,NaN,NaN,4.0,No,NaN,NaN,No,NaN,NaN,NaN,No,NaN,NaN,NaN,Yes,NaN,NaN,NaN,NaN,Positive,Positive,Negative,Negative,Negative,Negative,Negative,Negative,Negative,Negative,Negative,Negative,Negative,Negative,Negative,Negative,Negative,Negative,Negative,Negative,Negative,Negative,NaN,NaN,NaN,NaN,0.96,1.14,27/10/2020,NaN,NaN,NaN,40.0,83.0,65.0,65.0,131.0,No,Yes,1.2,3.0,0.5,27/10/2020,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NORMAL,No,No,No,No,No,No,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,SLE_map13436192,SLE_map13436192,AFR
1,EQTL041P,EQTL041Pr,NaN,Guys,Kings,18/05/2021,18/05/2021,2021,1984,37,30,White-British,2014,2014.0,7.0,30.0,NaN,NaN,NaN,NaN,NaN,2.0,"Low C4,C3",NaN,NaN,0.0,INACTIVE,INACTIVE,Yes,No,NaN,NaN,NaN,NaN,No,No,No,No,No,No,No,No,No,No,No,NaN,No,NaN,Yes,400/200 AD,No,NaN,No,NaN,No,NaN,Yes,75mg daily,No,NaN,No,NaN,No,NaN,No,No,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Positive,Positive,Negative,Positive,Positive,Negative,Negative,Negative,Negative,Negative,Negative,Negative,Negative,Negative,Negative,Positive,Negative,Negative,Negative,Negative,Negative,Negative,66.0,18/05/2021,2.06,18/05/2021,0.39,0.04,18/05/2021,NaN,NaN,NaN,42.0,55.0,108.0,90.0,126.0,No,No,1.0,4.0,0.2,18/05/2021,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,LOW,LOW,NORMAL,No,No,No,No,No,No,No,Yes,Yes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,SLE_map14749897,SLE_map14749897,EUR
2,EQTL073P,EQTL073P,NaN,Guys,Kings,09/11/2021,09/11/2021,2021,1990,31,30,White-British,2014,2014.0,7.0,24.0,NaN,NaN,NaN,NaN,NaN,0.0,none,NaN,NaN,0.0,INACTIVE,INACTIVE,Yes,No,NaN,NaN,NaN,NaN,No,No,No,No,No,No,No,No,No,No,No,NaN,No,NaN,Yes,400mg daily,No,NaN,No,NaN,No,NaN,No,NaN,No,NaN,NaN,NaN,No,NaN,NaN,No,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Positive,Positive,Negative,Negative,Negative,Negative,Negative,Negative,Negative,Negative,Negative,Negative,Negative,Negative,Negative,Negative,Negative,Negative,Negative,Negative,Negative,Negative,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NORMAL,Yes,No,No,No,No,No,No,No,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,SLE_WGS13446483,SLE_WGS13446483,EUR
3,EQTL0119P,EQTL119P,NaN,Guys,Kings,15/11/2022,15/11/2022,2022,1988,34,30,Black-Carribean,2008,2008.0,14.0,20.0,NaN,NaN,NaN,NaN,NaN,6.0,"Arthritis,Low C4",NaN,NaN,4.0,ACTIVE,INACTIVE,No,No,NaN,NaN,NaN,NaN,No,No,No,No,No,No,No,No,Yes,No,Yes,500mg bd,Yes,3mgOD,Yes,200mgbd,No,NaN,No,NaN,No,NaN,No,NaN,No,NaN,NaN,NaN,No,NaN,NaN,No,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Positive,Positive,Negative,Negative,Negative,Negative,Negative,Negative,Negative,Negative,Negative,Negative,Negative,Negative,Negative,Negative,Negative,Negative,Negative,Negative,Negative,Negative,NaN,NaN,NaN,NaN,0.97,0.07,15/11/2022,NaN,NaN,NaN,43.0,64.0,92.0,90.0,90.0,No,No,2.9,2.5,0.6,15/11/2022,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NORMAL,LOW,NORMAL,Yes,No,No,No,Yes,No,No,No,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,SLE_map13436179,SLE_map13436179,AFR
4,EQTL0138P,EQTL138P,NaN,Guys,Kings,08/02/2023,08/02/2023,2023,1976,47,40,African,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,none,NaN,NaN,0.0,INACTIVE,INACTIVE,No,No,NaN,NaN,NaN,NaN,No,No,No,No,No,No,No,No,No,No,Yes,1.5g am,Yes,1mg daily,Yes,200mgbd,No,NaN,No,NaN,No,NaN,No,NaN,No,NaN,NaN,NaN,Yes,NaN,NaN,No,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Positive,Positive,Negative,Negative,Negative,Negative,Negative,Positive,Positive,Negative,Negative,Negative,Negative,Negative,Negative,Negative,Negative,Negative,Negative,Negative,Negative,Negative,NaN,NaN,NaN,NaN,1.15,0.32,08/02/2023,NaN,NaN,NaN,41.0,45.0,132.0,90.0,114.0,No,Yes,1.0,1.5,0.2,08/02/2023,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Yes,No,No,No,No,No,No,No,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,SLE_map13764354,SLE_map13764354,AFR
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
283,S93,S93,S93,Imperial,Imperial,NaN,26/11/2019,2019,1968,51,50,White.Other,01/01/1997,1997.0,22.0,29.0,F,INACTIVE,NaN,NaN,NaN,2.0,NaN,4.0,0.0,0.0,INACTIVE,INACTIVE,No,Yes,13/03/2013,IV+III,III+IV,2.0,No,No,No,No,No,No,No,No,No,NaN,Yes,250mg_BD,Yes,5mg_OD,Yes,200mg_BD,No,NaN,No,NaN,No,NaN,No,NaN,Yes,Protocol,13/03/2013,2.0,No,NaN,NaN,Yes,1g,13/03/2013,NaN,No,NaN,NaN,0.0,NaN,46.0,IUperML,Positive,sample_date,NaN,Positive,Negative,Negative,Negative,Negative,Negative,Positive,Positive,Negative,Negative,Negative,Negative,Negative,Negative,Positive,Negative,Negative,Negative,Negative,Negative,Negative,91.1,24/09/2019,0.72,17/07/2019,0.85,0.21,sample_date,40.0,MGperMMOL,sample_date,36.0,136.0,39.0,39.0,132.0,No,Yes,1.5,3.4,0.4,sample_date,23.0,1.5,547.0,35.9,621.0,40.8,sample_date,1.66,13.2,1.25,sample_date,NORMAL,NORMAL,HIGH,Yes,No,No,No,No,No,No,Yes,Yes,02/01/2014,IV-S_(C)+V,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,SLE_WGS13446598,SLE_WGS13446598,AMR
284,S95,S95,S95,Imperial,Imperial,NaN,17/12/2019,2019,1977,42,40,Asian.Bangladeshi,01/11/2007,2007.0,12.0,30.0,F,INACTIVE,NaN,NaN,NaN,0.0,NaN,0.0,0.0,0.0,INACTIVE,INACTIVE,Yes,Yes,01/05/2008,V,V,1.0,No,Yes,Yes,No,No,No,No,No,No,DVT_Pulmonary_embolism,No,NaN,No,NaN,Yes,200mg_BD,No,NaN,No,NaN,No,NaN,No,NaN,No,NaN,NaN,0.0,No,NaN,NaN,Yes,1g,08/07/2008,1.0,No,NaN,NaN,0.0,NaN,0.0,IUperML,Negative,sample_date,Negative,Positive,Negative,Negative,Negative,Negative,Negative,Negative,Negative,Negative,Negative,Negative,Negative,Negative,Negative,NaN,NaN,NaN,NaN,NaN,NaN,NaN,103.4,06/03/2018,2.1,06/03/2018,1.03,0.27,sample_date,9.0,MGperMMOL,18/12/2019,44.0,68.0,90.0,90.0,133.0,No,No,2.5,3.3,0.7,sample_date,726.0,25.7,1016.0,37.9,844.0,31.5,30/10/2018,3.72,14.7,0.05,sample_date,NORMAL,NORMAL,NORMAL,Yes,No,No,No,No,No,No,No,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,SLE_map13436222,SLE_map13436222,SAS
285,S96,S96,S96,Imperial,Imperial,NaN,07/01/2020,2020,1950,70,70,Asian.Other,01/01/2006,2006.0,14.0,56.0,F,INACTIVE,NaN,NaN,NaN,0.0,NaN,0.0,0.0,0.0,INACTIVE,INACTIVE,Yes,Yes,01/01/2006,IV,IV,1.0,No,No,No,No,No,No,No,No,No,NaN,No,NaN,No,NaN,Yes,200mg_BD,No,NaN,No,NaN,No,NaN,No,NaN,No,NaN,NaN,0.0,No,NaN,NaN,No,NaN,NaN,0.0,No,NaN,NaN,0.0,NaN,11.0,IUperML,Negative,sample_date,NaN,Positive,Negative,Negative,Negative,Negative,Negative,Negative,Negative,Negative,Negative,Negative,Negative,Negative,Negative,Positive,Negative,Negative,Negative,Negative,Negative,Negative,75.0,21/05/2019,1.38,10/09/2019,1.50,0.18,sample_date,35.0,MGperMMOL,sample_date,41.0,63.0,86.0,86.0,133.0,No,Yes,1.3,8.1,1.1,sample_date,143.0,13.9,556.0,50.2,173.0,15.7,07/07/2020,1.95,10.7,3.39,sample_date,NORMAL,NORMAL,NORMAL,No,No,No,Yes,No,No,No,Yes,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,SLE_map13436227,SLE_map13436227,EUR
286,S99,S99,S99,Imperial,Imperial,NaN,14/01/2020,2020,1966,54,50,Asian.Indian,01/01/2001,2001.0,19.0,35.0,F,INACTIVE,NaN,NaN,NaN,0.0,NaN,0.0,0.0,0.0,INACTIVE,INACTIVE,Yes,Yes,01/11/2009,II+V,II+V,1.0,No,No,No,No,No,Yes,No,No,No,Pulmonary_TB_Hypothyroidism,Yes,500mg_BD,No,NaN,Yes,200mg_BD,No,NaN,No,NaN,No,NaN,No,NaN,No,NaN,NaN,0.0,No,NaN,NaN,No,NaN,NaN,0.0,No,NaN,NaN,0.0,NaN,10.0,IUperML,Negative,sample_date,NaN,Positive,Negative,Negative,Positive,Negative,Negative,Negative,Negative,Negative,Negative,Negative,Negative,Negative,Negative,NaN,NaN,NaN,NaN,NaN,NaN,NaN,90.2,sample_date,0.52,sample_date,1.45,0.41,sample_date,36.0,MGperMMOL,sample_date,42.0,118.0,45.0,45.0,131.0,No,No,1.8,3.2,0.4,sample_date,272.0,14.9,655.0,40.8,724.0,40.8,28/05/2019,1.33,14.3,0.35,sample_date,NORMAL,NORMAL,NORMAL,No,No,No,Yes,No,No,No,No,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,SLE_map13436217,SLE_map13436217,SAS
287,SC6,SC6,SC6,Imperial,Imperial,NaN,31/07/2019,2019,1982,37,30,Asian.Indian,01/01/1996,1996.0,23.0,14.0,F,INACTIVE,0.44,IFN-neg,IFN-low_neg,0.0,NaN,2.0,0.0,0.0,INACTIVE,INACTIVE,No,Yes,07/02/2018,V_transplant,V_transplant,1.0,No,No,No,No,No,No,No,No,No,ESKD,No,NaN,Yes,5mg_OD,Yes,100mg_BD,Yes,50mg_OD,No,NaN,No,NaN,No,NaN,Yes,Protocol,01/01/1998,6.0,No,NaN,NaN,Yes,1g,31/07/2019,2.0,No,NaN,NaN,0.0,NaN,0.0,UNITperML,Negative,25/06/2019,NaN,Positive,Negative,Negative,Negative,Negative,Negative,Negative,Negative,Negative,Negative,Negative,Negative,Negative,Negative,Negative,Negative,Negative,Negative,Negative,Negative,Negative,92.4,25/09/2018,0.98,25/09/2018,0.93,0.17,07/05/2019,16.0,MGperMMOL,25/06/2019,23.0,103.0,60.0,60.0,115.0,No,Yes,2.7,11.5,1.2,sample_date,8.0,2.0,161.0,40.2,201.0,50.1,sample_date,3.44,11.5,0.33,10/09/2019,NORMAL,NORMAL,NORMAL,No,No,No,Yes,No,No,No,Yes,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,SLE_map13436239,SLE_map13436239,SAS

In [9]:
obs_index = SLEmap.obs.index
SLEmap.obs = SLEmap.obs.merge(ancestry[["WGS_ID", "Ancestry"]],on="WGS_ID",how="left")
SLEmap.obs.index = obs_index
SLEmap.obs

,experiment_id,condition,recruitment_centre,sex,externalID,WGS_ID,poolID,n_genes_by_counts,log1p_n_genes_by_counts,total_counts,log1p_total_counts,pct_counts_gene_group__mito_transcript,log1p_total_counts_gene_group__ribo_protein,log10_ngenes_by_count,normalization_factor,Azimuth:predicted.celltype.l1,Azimuth:predicted.celltype.l1.score,Azimuth:mapping.score.celltype.l1,Azimuth:predicted.celltype.l2,Azimuth:predicted.celltype.l2.score,Azimuth:mapping.score.celltype.l2,Celltypist:Immune_All_Low:n_counts,Celltypist:Immune_All_Low:predicted_labels,Celltypist:Immune_All_Low:over_clustering,Celltypist:Immune_All_Low:majority_voting,Celltypist:Immune_All_Low:conf_score,Celltypist:Immune_All_High:n_counts,Celltypist:Immune_All_High:predicted_labels,Celltypist:Immune_All_High:over_clustering,Celltypist:Immune_All_High:majority_voting,Celltypist:Immune_All_High:conf_score,VDJ,_scvi_labels,_scvi_batch,leiden_totalVI,annotation_BTother,Celltype_level1,Celltype_level2,T_cluster,donor_id,Celltype_level0,Ancestry
index,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
AAACCTGTCCTATTCA-1-SLE_WGS13446475_LDP01__donor,SLE_WGS13446475_LDP01,SLE,Kings,F,EQTL083P,SLE_WGS13446475,LDP01,2748,7.918992,9784.0,9.188606,0.511038,7.884200,0.861797,9784.0,B,0.972145262054306,0.988524387890834,B memory,0.454549172518525,0.988524387890834,9784.0,Age-associated B cells,2,Age-associated B cells,0.999181776250646,9784.0,B cells,2,B cells,0.998594147977526,NaN,0,0,21,B,Naive_B_cells,Naive_B_cells,NA,SLE_WGS13446475,All,EAS
AAACGGGGTTGCGTTA-1-SLE_WGS13446475_LDP01__donor,SLE_WGS13446475_LDP01,SLE,Kings,F,EQTL083P,SLE_WGS13446475,LDP01,1779,7.484369,4606.0,8.435332,1.020408,6.966967,0.887220,4606.0,NK,0.901415102308412,0.977126889715796,NK_CD56bright,0.52491221770141,0.977126889715796,4606.0,NK cells,0,CD16+ NK cells,0.0708510702346563,4606.0,ILC,0,ILC,0.99989144988027,NaN,0,0,24,Other,CD56Bright_NK_cells,CD56Bright_NK_cells,NA,SLE_WGS13446475,All,EAS
AAAGATGCACGCTTTC-1-SLE_WGS13446475_LDP01__donor,SLE_WGS13446475_LDP01,SLE,Kings,F,EQTL083P,SLE_WGS13446475,LDP01,1242,7.125283,3298.0,8.101375,0.758035,7.049255,0.879449,3298.0,NK,0.98407663926649,0.999135264387835,NK,0.562969443244527,0.999135264387835,3298.0,NK cells,0,CD16+ NK cells,0.045185300626458,3298.0,ILC,0,ILC,0.993330058443046,NaN,0,0,24,Other,CD56Dim_NK_cells,CD56Dim_NK_cells,NA,SLE_WGS13446475,All,EAS
AAAGATGCACTTAAGC-1-SLE_WGS13446475_LDP01__donor,SLE_WGS13446475_LDP01,SLE,Kings,F,EQTL083P,SLE_WGS13446475,LDP01,1247,7.129298,3434.0,8.141772,0.728014,7.066467,0.875577,3434.0,CD4 T,1.0,0.99147377595226,CD4 TCM,0.81208480584909,0.99147377595226,3434.0,Tcm/Naive helper T cells,4,Tcm/Naive helper T cells,0.8427473161879951,3434.0,T cells,4,T cells,0.9997996498249444,TCR,0,0,27,T,Naive_CD4_T_cells,Naive_CD4_T_cells,21,SLE_WGS13446475,All,EAS
AAAGCAAAGATCTGAA-1-SLE_WGS13446475_LDP01__donor,SLE_WGS13446475_LDP01,SLE,Kings,F,EQTL083P,SLE_WGS13446475,LDP01,942,6.849066,3417.0,8.136811,1.082821,7.419980,0.841638,3417.0,CD4 T,0.97604889871704,0.981848325930261,CD4 Naive,0.879846881137276,0.981848325930261,3417.0,Tcm/Naive helper T cells,8,Tcm/Naive helper T cells,0.9993313697095632,3417.0,T cells,8,T cells,0.9999992926505225,TCR,0,0,27,T,Naive_CD4_T_cells,Naive_CD4_T_cells,21,SLE_WGS13446475,All,EAS
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
TTTGGTTCAGGGTACA-1-SLE_map14783141_LDP37__donor,SLE_map14783141_LDP37,SLE,Imperial,F,S104,SLE_map14783141,LDP37,2048,7.625107,5177.0,8.552175,1.062391,7.368340,0.891562,5177.0,B,1.0,0.933196017236146,B naive,0.943943398330885,0.933196017236146,5177.0,Naive B cells,8,Naive B cells,0.9990347591818896,5177.0,B cells,8,B cells,0.9999962181013616,BCR,0,36,1,B,Naive_B_cells,Naive_B_cells,NA,SLE_map14783141,All,SAS
TTTGGTTTCAGTCCCT-1-SLE_map14783141_LDP37__donor,SLE_map14783141_LDP37,SLE,Imperial,F,S104,SLE_map14783141,LDP37,1706,7.442493,3695.0,8.215007,3.761840,6.773080,0.905922,3695.0,B,1.0,0.831490592526736,B naive,0.976474963344939,0.831490592526736,3695.0,Naive B cells,20,Naive B cells,0.987242509123214,3695.0,B cells,20,B cells,0.9999999928278952,BCR,0,36,1,B,Naive_B_cells,Naive_B_cells,NA,SLE_map14783141,All,SAS
TTTGGTTTCGGTTAAC-1-SLE_map14783141_LDP37__donor,SLE_map14783141_LDP37,SLE,Imperial,F,S104,SLE_map14783141,LDP37,2185,7.689829,5282.0,8.572249,2.442257,7.202661,0.897027,5282.0,CD8 T,0.936699234768641,0.945268704577058,CD8 TEM,0.936699234768641,0.945268704577058,5282.0,Tem/Trm cytotoxic T cells,19,Tem/Temra cytotoxic T cells,0.9960462654735444,5282.0,T cells,19,T cells,0.999989386080858,TCR,0,36,3,T,TEMRA,TEMRA,6,SLE_map14783141,All,SAS
TTTGTCAAGATCTGCT-1-SLE_map14783141_LDP37__donor,SLE_map14783141_LDP37,SLE,Imperial,F,S104,SLE_map14783141,LDP37,1668,7.419980,3882.0,8.264363,2.988151,7.038784,0.897784,3882.0,CD8 T,0.935073171531549,0.953343230333327,CD8 TEM,0.730176942847057,0.953343230333327,3882.0,Tem/Trm cytotoxic T cells,6,Tem/Trm cytotoxic T cells,0.9967595521393606,3882.0,T cells,6,T cells,0.9999999228892832,TCR,0,36,9,T,EM_CD8_T_cells,EM_CD8_T_cells,2,SLE_map14783141,All,SAS
TTTGTCATCATGTCTT-1-SLE_map14783141_LDP37__donor,SLE_map14783141_LDP37,SLE,Imperial,F,S104,SLE_map14783141,LDP37,1747,7.466228,4039.0,8.304000,2.376826,7.031741,0.899070,4039.0,CD8 T,0.9809182216931,0.961255972772291,CD8 TEM,0.902039217937397,0.961255972772291,4039.0,Tem/Trm cytotoxic T cells,22,Tem/Trm cytotoxic T cells,0.9684964443656396,4039.0,T cells,22,T cells,0.9999999245397488,TCR,0,36,9,T,EM_CD8_T_cells,EM_CD8_T_cells,2,SLE_map14783141,All,SAS

In [12]:
SLEmap.obs["Ancestry"].value_counts()

Ancestry
AFR            235307
EUR            182228
SAS            134808
EAS             41726
AMR             14055
EUR;AMR          3683
EUR;AFR          2578
EUR;EAS          2078
EAS;AMR          2021
EAS;EUR;AMR      2000
AFR;EUR          1968
Name: count, dtype: int64

In [14]:
SLEmap

AnnData object with n_obs × n_vars = 622452 × 36600
    obs: 'experiment_id', 'condition', 'recruitment_centre', 'sex', 'externalID', 'WGS_ID', 'poolID', 'n_genes_by_counts', 'log1p_n_genes_by_counts', 'total_counts', 'log1p_total_counts', 'pct_counts_gene_group__mito_transcript', 'log1p_total_counts_gene_group__ribo_protein', 'log10_ngenes_by_count', 'normalization_factor', 'Azimuth:predicted.celltype.l1', 'Azimuth:predicted.celltype.l1.score', 'Azimuth:mapping.score.celltype.l1', 'Azimuth:predicted.celltype.l2', 'Azimuth:predicted.celltype.l2.score', 'Azimuth:mapping.score.celltype.l2', 'Celltypist:Immune_All_Low:n_counts', 'Celltypist:Immune_All_Low:predicted_labels', 'Celltypist:Immune_All_Low:over_clustering', 'Celltypist:Immune_All_Low:majority_voting', 'Celltypist:Immune_All_Low:conf_score', 'Celltypist:Immune_All_High:n_counts', 'Celltypist:Immune_All_High:predicted_labels', 'Celltypist:Immune_All_High:over_clustering', 'Celltypist:Immune_All_High:majority_voting', 'Celltypist:Immune_All_High:conf_score', 'VDJ', '_scvi_labels', '_scvi_batch', 'leiden_totalVI', 'annotation_BTother', 'Celltype_level1', 'Celltype_level2', 'T_cluster', 'donor_id', 'Celltype_level0', 'Ancestry'
    var: 'gene_symbols', 'gene_group__mito_transcript', 'gene_group__ribo_protein', 'n_cells_by_counts', 'mean_counts', 'log1p_mean_counts', 'pct_dropout_by_counts', 'total_counts', 'log1p_total_counts', 'highly_variable'
    uns: 'Azimuth:predicted.celltype.l1_colors', 'Azimuth:predicted.celltype.l2_colors', 'VDJ_colors', '_scvi_manager_uuid', '_scvi_uuid', 'hvg', 'leiden_totalVI', 'leiden_totalVI_colors', 'log1p', 'neighbors', 'umap'
    obsp: 'connectivities', 'distances'

In [13]:
SLEmap_EUR = SLEmap[SLEmap.obs["Ancestry"] == "EUR"].copy()
SLEmap_EUR
SLEmap_EUR.write("/lustre/scratch127/open-targets/Projects/OTAR2064/working/users/hj10/Results/20_ancestry_coloc/EUR/inputs/singlecell_input_n81_EUR.h5ad")

AnnData object with n_obs × n_vars = 182228 × 36600
    obs: 'experiment_id', 'condition', 'recruitment_centre', 'sex', 'externalID', 'WGS_ID', 'poolID', 'n_genes_by_counts', 'log1p_n_genes_by_counts', 'total_counts', 'log1p_total_counts', 'pct_counts_gene_group__mito_transcript', 'log1p_total_counts_gene_group__ribo_protein', 'log10_ngenes_by_count', 'normalization_factor', 'Azimuth:predicted.celltype.l1', 'Azimuth:predicted.celltype.l1.score', 'Azimuth:mapping.score.celltype.l1', 'Azimuth:predicted.celltype.l2', 'Azimuth:predicted.celltype.l2.score', 'Azimuth:mapping.score.celltype.l2', 'Celltypist:Immune_All_Low:n_counts', 'Celltypist:Immune_All_Low:predicted_labels', 'Celltypist:Immune_All_Low:over_clustering', 'Celltypist:Immune_All_Low:majority_voting', 'Celltypist:Immune_All_Low:conf_score', 'Celltypist:Immune_All_High:n_counts', 'Celltypist:Immune_All_High:predicted_labels', 'Celltypist:Immune_All_High:over_clustering', 'Celltypist:Immune_All_High:majority_voting', 'Celltypist:Immune_All_High:conf_score', 'VDJ', '_scvi_labels', '_scvi_batch', 'leiden_totalVI', 'annotation_BTother', 'Celltype_level1', 'Celltype_level2', 'T_cluster', 'donor_id', 'Celltype_level0', 'Ancestry'
    var: 'gene_symbols', 'gene_group__mito_transcript', 'gene_group__ribo_protein', 'n_cells_by_counts', 'mean_counts', 'log1p_mean_counts', 'pct_dropout_by_counts', 'total_counts', 'log1p_total_counts', 'highly_variable'
    uns: 'Azimuth:predicted.celltype.l1_colors', 'Azimuth:predicted.celltype.l2_colors', 'VDJ_colors', '_scvi_manager_uuid', '_scvi_uuid', 'hvg', 'leiden_totalVI', 'leiden_totalVI_colors', 'log1p', 'neighbors', 'umap'
    obsp: 'connectivities', 'distances'

In [16]:
SLEmap_AFR = SLEmap[SLEmap.obs["Ancestry"] == "AFR"].copy()
SLEmap_AFR.write("/lustre/scratch127/open-targets/Projects/OTAR2064/working/users/hj10/Results/20_ancestry_coloc/AFR/inputs/singlecell_input_n102_AFR.h5ad")
SLEmap_AFR

AnnData object with n_obs × n_vars = 235307 × 36600
    obs: 'experiment_id', 'condition', 'recruitment_centre', 'sex', 'externalID', 'WGS_ID', 'poolID', 'n_genes_by_counts', 'log1p_n_genes_by_counts', 'total_counts', 'log1p_total_counts', 'pct_counts_gene_group__mito_transcript', 'log1p_total_counts_gene_group__ribo_protein', 'log10_ngenes_by_count', 'normalization_factor', 'Azimuth:predicted.celltype.l1', 'Azimuth:predicted.celltype.l1.score', 'Azimuth:mapping.score.celltype.l1', 'Azimuth:predicted.celltype.l2', 'Azimuth:predicted.celltype.l2.score', 'Azimuth:mapping.score.celltype.l2', 'Celltypist:Immune_All_Low:n_counts', 'Celltypist:Immune_All_Low:predicted_labels', 'Celltypist:Immune_All_Low:over_clustering', 'Celltypist:Immune_All_Low:majority_voting', 'Celltypist:Immune_All_Low:conf_score', 'Celltypist:Immune_All_High:n_counts', 'Celltypist:Immune_All_High:predicted_labels', 'Celltypist:Immune_All_High:over_clustering', 'Celltypist:Immune_All_High:majority_voting', 'Celltypist:Immune_All_High:conf_score', 'VDJ', '_scvi_labels', '_scvi_batch', 'leiden_totalVI', 'annotation_BTother', 'Celltype_level1', 'Celltype_level2', 'T_cluster', 'donor_id', 'Celltype_level0', 'Ancestry'
    var: 'gene_symbols', 'gene_group__mito_transcript', 'gene_group__ribo_protein', 'n_cells_by_counts', 'mean_counts', 'log1p_mean_counts', 'pct_dropout_by_counts', 'total_counts', 'log1p_total_counts', 'highly_variable'
    uns: 'Azimuth:predicted.celltype.l1_colors', 'Azimuth:predicted.celltype.l2_colors', 'VDJ_colors', '_scvi_manager_uuid', '_scvi_uuid', 'hvg', 'leiden_totalVI', 'leiden_totalVI_colors', 'log1p', 'neighbors', 'umap'
    obsp: 'connectivities', 'distances'

In [17]:
SLEmap_SAS = SLEmap[SLEmap.obs["Ancestry"] == "SAS"].copy()
SLEmap_SAS.write("/lustre/scratch127/open-targets/Projects/OTAR2064/working/users/hj10/Results/20_ancestry_coloc/SAS/inputs/singlecell_input_n62_SAS.h5ad")
SLEmap_SAS

AnnData object with n_obs × n_vars = 134808 × 36600
    obs: 'experiment_id', 'condition', 'recruitment_centre', 'sex', 'externalID', 'WGS_ID', 'poolID', 'n_genes_by_counts', 'log1p_n_genes_by_counts', 'total_counts', 'log1p_total_counts', 'pct_counts_gene_group__mito_transcript', 'log1p_total_counts_gene_group__ribo_protein', 'log10_ngenes_by_count', 'normalization_factor', 'Azimuth:predicted.celltype.l1', 'Azimuth:predicted.celltype.l1.score', 'Azimuth:mapping.score.celltype.l1', 'Azimuth:predicted.celltype.l2', 'Azimuth:predicted.celltype.l2.score', 'Azimuth:mapping.score.celltype.l2', 'Celltypist:Immune_All_Low:n_counts', 'Celltypist:Immune_All_Low:predicted_labels', 'Celltypist:Immune_All_Low:over_clustering', 'Celltypist:Immune_All_Low:majority_voting', 'Celltypist:Immune_All_Low:conf_score', 'Celltypist:Immune_All_High:n_counts', 'Celltypist:Immune_All_High:predicted_labels', 'Celltypist:Immune_All_High:over_clustering', 'Celltypist:Immune_All_High:majority_voting', 'Celltypist:Immune_All_High:conf_score', 'VDJ', '_scvi_labels', '_scvi_batch', 'leiden_totalVI', 'annotation_BTother', 'Celltype_level1', 'Celltype_level2', 'T_cluster', 'donor_id', 'Celltype_level0', 'Ancestry'
    var: 'gene_symbols', 'gene_group__mito_transcript', 'gene_group__ribo_protein', 'n_cells_by_counts', 'mean_counts', 'log1p_mean_counts', 'pct_dropout_by_counts', 'total_counts', 'log1p_total_counts', 'highly_variable'
    uns: 'Azimuth:predicted.celltype.l1_colors', 'Azimuth:predicted.celltype.l2_colors', 'VDJ_colors', '_scvi_manager_uuid', '_scvi_uuid', 'hvg', 'leiden_totalVI', 'leiden_totalVI_colors', 'log1p', 'neighbors', 'umap'
    obsp: 'connectivities', 'distances'

## make files for vcf filtering

In [19]:
eur_ids = ancestry.loc[ancestry["Ancestry"] == "EUR", "WGS_ID"].dropna().astype(str).drop_duplicates()
n_eur = len(eur_ids)
print(f"Number of EUR samples: {n_eur}")
eur_ids.to_csv("/lustre/scratch127/open-targets/Projects/OTAR2064/working/users/hj10/Results/20_ancestry_coloc/EUR/inputs/EUR_samples.txt", index=False, header=False)

Number of EUR samples: 81

In [20]:
afr_ids = ancestry.loc[ancestry["Ancestry"] == "AFR", "WGS_ID"].dropna().astype(str).drop_duplicates()
n_afr = len(afr_ids)
print(f"Number of AFR samples: {n_afr}")
afr_ids.to_csv("/lustre/scratch127/open-targets/Projects/OTAR2064/working/users/hj10/Results/20_ancestry_coloc/AFR/inputs/AFR_samples.txt", index=False, header=False)

Number of AFR samples: 102

In [21]:
sas_ids = ancestry.loc[ancestry["Ancestry"] == "SAS", "WGS_ID"].dropna().astype(str).drop_duplicates()
n_sas = len(sas_ids)
print(f"Number of SAS samples: {n_sas}")
sas_ids.to_csv("/lustre/scratch127/open-targets/Projects/OTAR2064/working/users/hj10/Results/20_ancestry_coloc/SAS/inputs/SAS_samples.txt", index=False, header=False)

Number of SAS samples: 62